### ISSUE TITLE
11장. 데브옵스

### ISSUE THREAD

**Issue by KS-KIM** [Woohan-TDD/book-aws-study#11]

**Comment by aegis1920** [comment]
p.298 에서 '1개 이상의 템플렛에서 새로운 역할을 생성합니다'가 없고, 그냥 AWS 정책 템플릿에서 새 역할 생성을 클릭하시면 됩니다.

![Screen Shot 2021-04-15 at 3 19 08 PM](https://user-images.githubusercontent.com/22311557/114826296-48985c80-9e02-11eb-8c04-47853a91dc09.png)

Lambda 편집기에 넣을 소스코드입니다. (그대로 가져다 붙이시면 됩니다)
[https://gist.github.com/deopard/3767b4f96bc9760c5dc7ce45d30647bb](https://gist.github.com/deopard/3767b4f96bc9760c5dc7ce45d30647bb)

**Comment by KS-KIM** [comment]
### aws codebuild 추가하여 java application 빌드하기

프로젝트 루트에 buildspec.yml을 정의합니다. 수행 과정은 다음과 같습니다.

1. 빌드 phase에서 gradle build를 수행합니다.
2. 빌드 후 jar파일을 루트로 옮깁니다.
3. 이동한 jar파일을 아티팩트로 지정합니다.
```yml
version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - mv ./build/libs/*.jar application.jar

artifacts:
  files:
    - application.jar
```

[이 글](https://jojoldu.tistory.com/283?category=777282)을 참고했는데, 우리는 elastic beanstalk를 통해 배포하기 때문에 buildspec 내용이 조금 다릅니다.

[이 글](https://docs.aws.amazon.com/codebuild/latest/userguide/sample-elastic-beanstalk.html)이 maven인것만 빼면 레퍼런스라서 참고하기 더 좋습니다.
